"""
Database initialization scripts, schemas, and connection helpers.
"""
from typing import Dict
from stackforge.core.config import StackConfig

def get_database_files(config: StackConfig) -> Dict[str, str]:
    files = {}
    db = config.database
    name = config.project_name

    if db == "none":
        return files

    if db == "postgresql":
        files["database/init.sql"] = f"""-- Database Initialization for {name}
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO items (name, description) VALUES
    ('Architecture Scaffolding', 'Fast bootstrap generated by StackForge'),
    ('Container Registry', 'Docker images with optimized layers')
ON CONFLICT DO NOTHING;
"""
    elif db == "mongodb":
        files["database/mongo-init.js"] = f"""// MongoDB Initialization for {name}
db = db.getSiblingDB('{name}');

db.createCollection('items');

db.items.insertMany([
  {{
    name: 'MongoDB Document Storage',
    description: 'Flexible JSON documents configured for microservices',
    createdAt: new Date()
  }},
  {{
    name: 'StackForge Generator',
    description: 'Automated CI/CD DevOps pipeline integration',
    createdAt: new Date()
  }}
]);
"""
    elif db == "redis":
        files["database/redis.conf"] = """# Redis Configuration for Cache Layer
maxmemory 256mb
maxmemory-policy allkeys-lru
save 60 1
loglevel notice
"""
    elif db == "sqlite":
        files["database/schema.sql"] = """-- SQLite Initial Schema
CREATE TABLE IF NOT EXISTS items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    description TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO items (name, description) VALUES
    ('Embedded SQLite DB', 'Zero-configuration database for fast prototyping');
"""
    elif db == "mysql":
        files["database/init.sql"] = f"""-- MySQL Initialization for {name}
CREATE DATABASE IF NOT EXISTS `{name}`;
USE `{name}`;

CREATE TABLE IF NOT EXISTS `items` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO `items` (`name`, `description`) VALUES
    ('MySQL Database', 'Enterprise relational persistence');
"""

    return files
